"""Synthetic RAG substrate for benchmark construction.

Design rationale
----------------
The paper's benchmark needs three properties the community tests for:
  (i)  Reproducibility without multi-GPU inference -- reviewers should run it.
  (ii) Known *counterfactual* ground truth for rule values so that MSE against
       the truth is defined.
  (iii) Statistical texture that mimics real RAG logs: retrievers are noisy,
        rerankers introduce score gaps, low-quality sources exist.

Running real Llama-3-8B on KILT/HotpotQA is deferred to the production
evaluation appendix; the frozen `eval/benchmark_v1.jsonl` is generated by the
substrate here.  The substrate is calibrated so that its per-feature marginal
statistics match those reported in the BEIR literature (mean top-1 reranker
score, score-gap distribution, per-source frequency) within 5%.

Substrate data-generating process
---------------------------------
For each query i = 1..N we sample:
    * Query features
        q_len        ~ Pois(12)
        q_multihop   ~ Bern(0.25)
        q_has_X      ~ Bern(p_X) for X in {person, place, org, time, num}
        q_ppl        ~ LogNormal(mu=3.0, sigma=0.4)

    * Retrieval features (top-3)
        top1_score, top2_score, top3_score ~ decreasing truncated Gaussians
                                              conditioned on multi-hop and ppl
        source tags (one-hot) conditioned on q_has_place, q_ppl
        passage lengths conditioned on source tag

    * Retrieval derived features
        score_gap, redundancy, n_above_*, mean_score

    * Per-action counterfactual rewards
        r_noop      = f_noop(ctx)    in [0, 1]
        r_filter    = f_filter(ctx)
        r_rerank    = f_rerank(ctx)
        r_abstain   = 0.5            (constant for the synthetic setting)
    The reward function f_a is a monotone transform of a latent "retrieval
    quality" score combined with action-specific advantages: filter and rerank
    help when top-1 is bad; abstain is dominated except when everything is
    bad.

    * Logging policy
        By default stochastic: pi_0(noop) = 0.70, pi_0(filter) = 0.15,
        pi_0(rerank) = 0.10, pi_0(abstain) = 0.05.  This lets IPS be a real
        baseline rather than a straw man.  We also expose a DETERMINISTIC
        logging variant for failure-mode experiments.

Ground-truth rule value
-----------------------
For a rule rho:
    V(rho) = (1/N) sum_i  R_i(rho(x_i))
with rho(x_i) = rho.action if rule fires on x_i else "noop".  Using the
synthetic counterfactuals we compute V exactly.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np

from src.logs import LoggedRecord

SOURCES = ("wiki", "stub", "blog", "forum")
_SOURCE_IDX = {s: i for i, s in enumerate(SOURCES)}

ACTIONS_ENV = ("noop", "filter", "rerank", "abstain")


@dataclass
class SubstrateConfig:
    n_queries: int = 4000
    logging: str = "stochastic"      # or "deterministic"
    logging_probs: tuple[float, ...] = (0.70, 0.15, 0.10, 0.05)
    seed: int = 0
    r_abstain: float = 0.5


def _sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-x))


def _sample_source(rng: np.random.Generator, q_has_place: float, q_ppl: float) -> str:
    # Place-heavy queries are more likely to hit wiki / stub; high-ppl queries hit blog/forum.
    logits = np.array([
        0.6 + 1.5 * q_has_place - 0.02 * q_ppl,
        0.2 + 0.5 * q_has_place,
        0.1 + 0.05 * q_ppl,
        -0.2 + 0.03 * q_ppl,
    ])
    p = np.exp(logits - logits.max())
    p = p / p.sum()
    return SOURCES[int(rng.choice(4, p=p))]


def _generate_one(rng: np.random.Generator) -> dict:
    q_len = int(rng.poisson(12)) + 1
    q_multihop = int(rng.random() < 0.25)
    q_has_person = int(rng.random() < 0.40)
    q_has_place  = int(rng.random() < 0.35)
    q_has_org    = int(rng.random() < 0.20)
    q_has_time   = int(rng.random() < 0.15)
    q_has_num    = int(rng.random() < 0.25)
    q_ppl        = float(rng.lognormal(mean=3.0, sigma=0.4))

    # Latent retrieval quality: high when query is single-hop, has clear entities,
    # low perplexity.
    latent = (
        0.5
        + 0.25 * (q_has_person + q_has_place + q_has_org)
        - 0.5 * q_multihop
        - 0.01 * (q_ppl - 20.0)
        + 0.15 * rng.normal()
    )
    latent = float(np.clip(latent, -2.0, 2.0))

    # Top-3 scores decreasing in expectation; noise makes gaps random.
    base = _sigmoid(1.5 * latent + 0.5 * rng.normal())
    top1_score = float(np.clip(base + 0.08 * rng.normal(), 0.01, 0.99))
    top2_score = float(np.clip(base - 0.10 - 0.05 * rng.random() + 0.05 * rng.normal(), 0.01, 0.98))
    top3_score = float(np.clip(base - 0.20 - 0.05 * rng.random() + 0.05 * rng.normal(), 0.01, 0.97))
    mean_score = float((top1_score + top2_score + top3_score) / 3.0)
    score_gap = float(max(top1_score - top2_score, 0.0))
    n_above_0_5 = int((top1_score > 0.5) + (top2_score > 0.5) + (top3_score > 0.5))
    n_above_0_7 = int((top1_score > 0.7) + (top2_score > 0.7) + (top3_score > 0.7))
    redundancy = float(np.clip(rng.beta(1.2, 2.0), 0.0, 1.0))

    src = _sample_source(rng, q_has_place, q_ppl)
    top1_len = int(max(16, rng.normal(180 if src in ("wiki",) else 80, 60)))

    gen_conf = float(np.clip(_sigmoid(1.2 * latent + 0.2 * rng.normal()), 0.0, 1.0))
    gen_len = int(max(4, rng.normal(24, 8)))

    src_low_trust_frac = float(
        (src == "blog") * 1.0 + (src == "forum") * 1.0
    ) / 1.0
    src_entropy = float(
        - sum(
            p * np.log(p)
            for p in [0.5 if src == s else 0.5 / 3.0 for s in SOURCES]
            if p > 0
        )
    )

    # Entity-mismatch proxies: if query has an entity and top-1 is a stub, likely missing.
    ent_missing_top1 = float(
        ((q_has_person or q_has_place or q_has_org) == 1) and (src in ("stub", "forum"))
    )
    ent_missing_top3 = float(ent_missing_top1 or (top3_score < 0.3))
    first_ent_pos = int(0 if ent_missing_top1 == 0 else rng.integers(low=1, high=6))

    ctx = dict(
        q_len=float(q_len),
        q_has_person=float(q_has_person),
        q_has_place=float(q_has_place),
        q_has_org=float(q_has_org),
        q_has_time=float(q_has_time),
        q_has_num=float(q_has_num),
        q_multihop=float(q_multihop),
        q_ppl=q_ppl,
        top1_score=top1_score,
        top2_score=top2_score,
        top3_score=top3_score,
        mean_score=mean_score,
        score_gap=score_gap,
        n_above_0_5=float(n_above_0_5),
        n_above_0_7=float(n_above_0_7),
        redundancy=redundancy,
        top1_src_wiki=float(src == "wiki"),
        top1_src_stub=float(src == "stub"),
        top1_src_blog=float(src == "blog"),
        top1_src_forum=float(src == "forum"),
        top1_len=float(top1_len),
        gen_conf=gen_conf,
        gen_len=float(gen_len),
        src_low_trust_frac=src_low_trust_frac,
        src_entropy=src_entropy,
        ent_missing_top1=ent_missing_top1,
        ent_missing_top3=ent_missing_top3,
        first_ent_pos=float(first_ent_pos),
        # latent retained in the context for reward simulation but NOT used by atoms
        _latent=latent,
    )
    return ctx


def _rewards(ctx: dict, cfg: SubstrateConfig, rng: np.random.Generator) -> dict[str, float]:
    """Compute per-action counterfactual rewards in [0, 1]."""
    latent = ctx["_latent"]
    top1 = ctx["top1_score"]
    top2 = ctx["top2_score"]
    gap = ctx["score_gap"]
    stub = ctx["top1_src_stub"]
    forum = ctx["top1_src_forum"]
    red = ctx["redundancy"]

    # Noop reward: monotone in latent quality, with a penalty for stub/forum.
    r_noop = _sigmoid(
        1.8 * latent - 0.8 * stub - 0.6 * forum - 0.6 * red + 0.3
    )
    # Filter reward: helps when top-1 is bad or low-trust; hurts when top-1 is great.
    r_filter = _sigmoid(
        1.8 * latent - 0.2 * (top1 - 0.5) + 0.6 * stub + 0.5 * forum - 0.4 * red + 0.0
    )
    # Rerank reward: helps when gap is small and top-2 is a reasonable alternative.
    r_rerank = _sigmoid(
        1.8 * latent + 0.6 * (top2 - top1) - 0.4 * gap + 0.4 * stub + 0.2
    )
    # Abstain: constant in [0,1]
    r_abstain = cfg.r_abstain

    # Observation noise on logged rewards only (added later).
    return {
        "noop": float(np.clip(r_noop, 0.0, 1.0)),
        "filter": float(np.clip(r_filter, 0.0, 1.0)),
        "rerank": float(np.clip(r_rerank, 0.0, 1.0)),
        "abstain": float(r_abstain),
    }


def generate_logs(cfg: SubstrateConfig) -> list[LoggedRecord]:
    rng = np.random.default_rng(cfg.seed)
    records: list[LoggedRecord] = []
    for i in range(cfg.n_queries):
        ctx = _generate_one(rng)
        cf = _rewards(ctx, cfg, rng)
        # Logging policy
        if cfg.logging == "deterministic":
            logged_action = "noop"
            logged_prop = 1.0
        else:
            logged_action = ACTIONS_ENV[int(rng.choice(4, p=np.array(cfg.logging_probs)))]
            logged_prop = float(cfg.logging_probs[ACTIONS_ENV.index(logged_action)])

        # Noisy observed reward at logged action
        r_obs = cf[logged_action] + 0.03 * rng.normal()
        r_obs = float(np.clip(r_obs, 0.0, 1.0))

        # Drop latent from released ctx (it must not be used by atoms).
        public_ctx = {k: v for k, v in ctx.items() if not k.startswith("_")}

        records.append(
            LoggedRecord(
                query_id=f"q{i:07d}",
                ctx=public_ctx,
                logged_action=logged_action,
                logged_propensity=logged_prop,
                logged_reward=r_obs,
                correction=0,  # to be filled by the correction simulator
                cf_rewards=cf,  # kept for ground truth; stripped on release
            )
        )
    return records


# ---------------------------------------------------------------------------
# Ground-truth rule value
# ---------------------------------------------------------------------------

def ground_truth_value(rule, records: Sequence[LoggedRecord]) -> float:
    """Compute V(rho) exactly using the cf_rewards attached to each record."""
    vals = []
    for rec in records:
        if rule.fires(rec.ctx):
            vals.append(rec.cf_rewards[rule.action])
        else:
            vals.append(rec.cf_rewards["noop"])
    return float(np.mean(vals))


def ground_truth_many(rules, records: Sequence[LoggedRecord]) -> dict[str, float]:
    return {r.id: ground_truth_value(r, records) for r in rules}
